import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState,useEffect } from 'react'
import { io } from 'socket.io-client'
let socket;
export default function Home() {
  const [username, setusername] = useState('username')
  const [message, setmessage] = useState('')
  const [messages, setmessages] = useState([])

   async function fetcServer(){
   await fetch('/api/socketio')
      socket= io()
      socket.on('updatedMessages',messages=>setmessages(messages))
  }

  useEffect(() => {
    fetcServer()
  }, [])

  const sendMessage = (e)=>{
    e.preventDefault()
     socket.emit('newMessage',[
      ...messages,
      {message, username}
    ])
  }
  const handleEnter= (e)=>{
    if (e.keyCode == 13) {
      sendMessage(e)
   }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex', justifyContent: 'center', flexDirection: 'column', gap: '20px', padding: '50px 10px' }}>
        <input type='text' value={username} onChange={(e) => setusername(e.target.value)} style={{ width: '100px' }} />
        {
          messages?.map((msg,index) => <>
            <div key={index} style={{ display: 'flex', justifyContent: 'center' }}>
              <p>{msg.username} : </p>
              <p>{msg.message}</p>
            </div>
          </>)
        }
        <div style={{ display: 'flex',gap:'10px'}}>
          <input type='text' value={message} onChange={(e) => setmessage(e.target.value)} style={{ width: '200px' }} onKeyUp={(e)=>handleEnter(e)} />
          <button type='button' style={{ width: '80px' }} onClick={(e)=>sendMessage(e)} >Potvrdi</button>
        </div>
      </div>
    </div>
  )
}
